version: "3"
services: 
    notification-server:
        build:
            context: .
            dockerfile: Dockerserverfile
        ports: 
            - "3000:3000"
        depends_on: 
            - mongo
            - redis
    pushnotification-service:
        build:
            context: .
            dockerfile: DockerPushNotificationfile
        depends_on: 
            - redis
    sms-service:
        build:
            context: .
            dockerfile: DockerSmsfile
        depends_on: 
            - redis

    mongo:
        image: mongo
        volumes: 
            - mongo-db:/data/db
    redis:
        image: redis
        
volumes: 
    mongo-db:

    