version: "3"
services: 
    notification-server:
        volumes: 
            - ./:/app
            - /app/node_modules
        environment: 
            - NODE_ENV=development
        command: npm run dev